//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.11 at 07:57:12 PM IST 
//


package com.usa.his.washingaton.inputmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EligibilityDetermination complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EligibilityDetermination">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="citigen-data" type="{}CitigenData"/>
 *         &lt;element name="plan-details" type="{}PlanDetails"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EligibilityDetermination", propOrder = {
    "citigenData",
    "planDetails"
})
public class EligibilityDetermination {

    @XmlElement(name = "citigen-data", required = true)
    protected CitigenData citigenData;
    @XmlElement(name = "plan-details", required = true)
    protected PlanDetails planDetails;

   

	/**
     * Gets the value of the citigenData property.
     * 
     * @return
     *     possible object is
     *     {@link CitigenData }
     *     
     */
    public CitigenData getCitigenData() {
        return citigenData;
    }

    /**
     * Sets the value of the citigenData property.
     * 
     * @param value
     *     allowed object is
     *     {@link CitigenData }
     *     
     */
    public void setCitigenData(CitigenData value) {
        this.citigenData = value;
    }

    /**
     * Gets the value of the planDetails property.
     * 
     * @return
     *     possible object is
     *     {@link PlanDetails }
     *     
     */
    public PlanDetails getPlanDetails() {
        return planDetails;
    }

    /**
     * Sets the value of the planDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlanDetails }
     *     
     */
    public void setPlanDetails(PlanDetails value) {
        this.planDetails = value;
    }

	@Override
	public String toString() {
		return "EligibilityDetermination [citigenData=" + citigenData + ", planDetails=" + planDetails + "]";
	}
    
    

}
