//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.11 at 07:57:12 PM IST 
//


package com.usa.his.washingaton.inputmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.usa.his.washingaton.outputmodel.PlanInfo;


/**
 * <p>Java class for MedicaidPlanData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MedicaidPlanData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="employment-income" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="properties-cost" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="other-income" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MedicaidPlanData", propOrder = {
    "employmentIncome",
    "propertiesCost",
    "otherIncome"
})
public class MedicaidPlanData {

   

	@XmlElement(name = "employment-income", required = true)
    protected String employmentIncome;
    @XmlElement(name = "properties-cost", required = true)
    protected String propertiesCost;
    @XmlElement(name = "other-income", required = true)
    protected String otherIncome;
   
    private PlanInfo plnInfo; 
    public PlanInfo getPlnInfo() {
		return plnInfo;
	}

	public void setPlnInfo(PlanInfo plnInfo) {
		this.plnInfo = plnInfo;
	}

	/**
     * Gets the value of the employmentIncome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmploymentIncome() {
        return employmentIncome;
    }

    /**
     * Sets the value of the employmentIncome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmploymentIncome(String value) {
        this.employmentIncome = value;
    }

    /**
     * Gets the value of the propertiesCost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropertiesCost() {
        return propertiesCost;
    }

    /**
     * Sets the value of the propertiesCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropertiesCost(String value) {
        this.propertiesCost = value;
    }

    /**
     * Gets the value of the otherIncome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherIncome() {
        return otherIncome;
    }

    /**
     * Sets the value of the otherIncome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherIncome(String value) {
        this.otherIncome = value;
    }
    
    @Override
   	public String toString() {
   		return "MedicaidPlanData [employmentIncome=" + employmentIncome + ", propertiesCost=" + propertiesCost
   				+ ", otherIncome=" + otherIncome + "]";
   	}

}
