//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.11 at 07:57:12 PM IST 
//


package com.usa.his.washingaton.inputmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

import com.usa.his.washingaton.outputmodel.PlanInfo;


/**
 * <p>Java class for SnapPlanData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SnapPlanData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="family-income" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="is-Employed" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SnapPlanData", propOrder = {
    "familyIncome",
    "isEmployed"
})
public class SnapPlanData {

    @XmlElement(name = "family-income", required = true)
    protected String familyIncome;
    @XmlElement(name = "is-Employed", required = true)
    protected String isEmployed;
    
    //@XmlTransient
    //@XmlElement(name = "plnInfo", required = true)
    private  PlanInfo plnInfo;
   
    
	public PlanInfo getPlnInfo() {
		return plnInfo;
	}

	public void setPlnInfo(PlanInfo plnInfo) {
		this.plnInfo = plnInfo;
	}

	/**
     * Gets the value of the familyIncome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFamilyIncome() {
        return familyIncome;
    }

    /**
     * Sets the value of the familyIncome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFamilyIncome(String value) {
        this.familyIncome = value;
    }

    /**
     * Gets the value of the isEmployed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsEmployed() {
        return isEmployed;
    }

    /**
     * Sets the value of the isEmployed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsEmployed(String value) {
        this.isEmployed = value;
    }
    
   
    @Override
	public String toString() {
		return "SnapPlanData [familyIncome=" + familyIncome + ", isEmployed=" + isEmployed + ", plnInfo=" + plnInfo
				+ "]";
	}

}
