//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.11 at 07:58:45 PM IST 
//


package com.usa.his.washingaton.outputmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PlanInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PlanInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="plan-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="plan-status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="case-num" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="plan-approved" type="{}PlanApproved"/>
 *         &lt;element name="plan-denied" type="{}PlanDenied"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PlanInfo", propOrder = {
    "planName",
    "planStatus",
    "caseNum",
    "planApproved",
    "planDenied"
})
public class PlanInfo {

    @XmlElement(name = "plan-name", required = true)
    protected String planName;
    @XmlElement(name = "plan-status", required = true)
    protected String planStatus;
    @XmlElement(name = "case-num", required = true)
    protected String caseNum;
    @XmlElement(name = "plan-approved", required = true)
    protected PlanApproved planApproved;
    @XmlElement(name = "plan-denied", required = true)
    protected PlanDenied planDenied;

    @Override
	public String toString() {
		return "PlanInfo [planName=" + planName + ", planStatus=" + planStatus + ", caseNum=" + caseNum
				+ ", planApproved=" + planApproved + ", planDenied=" + planDenied + "]";
	}

	/**
     * Gets the value of the planName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanName() {
        return planName;
    }

    /**
     * Sets the value of the planName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanName(String value) {
        this.planName = value;
    }

    /**
     * Gets the value of the planStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanStatus() {
        return planStatus;
    }

    /**
     * Sets the value of the planStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanStatus(String value) {
        this.planStatus = value;
    }

    /**
     * Gets the value of the caseNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaseNum() {
        return caseNum;
    }

    /**
     * Sets the value of the caseNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaseNum(String value) {
        this.caseNum = value;
    }

    /**
     * Gets the value of the planApproved property.
     * 
     * @return
     *     possible object is
     *     {@link PlanApproved }
     *     
     */
    public PlanApproved getPlanApproved() {
        return planApproved;
    }

    /**
     * Sets the value of the planApproved property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlanApproved }
     *     
     */
    public void setPlanApproved(PlanApproved value) {
        this.planApproved = value;
    }

    /**
     * Gets the value of the planDenied property.
     * 
     * @return
     *     possible object is
     *     {@link PlanDenied }
     *     
     */
    public PlanDenied getPlanDenied() {
        return planDenied;
    }

    /**
     * Sets the value of the planDenied property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlanDenied }
     *     
     */
    public void setPlanDenied(PlanDenied value) {
        this.planDenied = value;
    }

}
